services:
  - type: web
    name: darkbyte-crew-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USERNAME
        value: DarkByteCrew
      - key: ADMIN_IDS
        sync: false
      - key: DB_HOST
        value: sql201.infinityfree.com
      - key: DB_USER
        value: if0_41322982
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: if0_41322982_darkbytecre
      - key: DB_PORT
        value: 3306
      - key: WEB_PORT
        value: 3000
      - key: BASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
    healthCheckPath: /health